services:
    database:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    reverseproxy:
        build: reverseproxy
        ports:
            - 8080:8080
        restart: always

    frontend:
        build: web
        depends_on:
            - reverseproxy
        restart: always

    backend:
        depends_on:
            - reverseproxy
            - database
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        build: backend
        restart: always
