services:
    database:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - database-volume:/var/lib/postgresql/data

    reverseproxy:
        build: reverseproxy
        ports:
            - 8080:8080
        restart: always

    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./web
        command: [ "/bin/bash", "-c", "npm run dev" ]
        depends_on:
            - reverseproxy
        restart: always
        volumes:
            - ./web/frontend:/frontend

    backend:
        depends_on:
            - reverseproxy
            - database
        command:
            [
                "/bin/bash",
                "-c",
                "python3 /backend/app/migrate.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        build: backend
        restart: always
        volumes:
            - ./backend/src:/backend/app

volumes:
    database-volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${PWD}/postgres_data'
